#!/usr/bin/env zsh
# This hook is run after every virtualenv is activated.

PS1="$_OLD_VIRTUAL_PS1"
_OLD_RPROMPT="$RPROMPT"
export _OLD_PROMPT="$PROMPT"
RPROMPT="%{${fg_bold[white]}%}(%{${fg[green]}%}`basename $(echo $VIRTUAL_ENV)`%{${fg_bold[white]}%})%{${reset_color}%} $RPROMPT"

